# Generated by Django 5.0.2 on 2024-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
